<?php

/**
 * @file
 *
 *
 */

/*
 * Implementation of hook_menu.
 *
 */

function eurostar_train_search_menu() {
  $items['eurostar-train-search/autocoplete/from'] = array(
    'title' => t('Train details'),
    'page callback' => 'eurostar_train_search_autocomplete_from',
    'page arguments' => array(3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['eurostar-train-search/autocoplete/to'] = array(
    'title' => t('Train details'),
    'page callback' => 'eurostar_train_search_autocomplete_to',
    'page arguments' => array(3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['eurostar-train-search/test'] = array(
    'title' => t('Train Search form'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('eurostar_train_search_form'),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 *  Custom form for the train search
 *
 */
function eurostar_train_search_form() {
  $form['from'] = array(
    '#title' => t('From'),
    '#type' => 'textfield',
    // Not for scenario 1
    // '#autocomplete_path' => 'eurostar-train-search/autocoplete/from'
   );
  $form['to'] = array(
    '#title' => t('To'),
    '#type' => 'textfield',
    // Not for scenario 1
    // '#autocomplete_path' => 'eurostar-train-search/autocoplete/to'
  );

  $form['hotel'] = array(
    '#type' => 'checkbox',
    '#title' => t('Add a hotel and save money'),
  );
  $form['depart'] = array(
    '#title' => t('Depart'),
    '#type' => 'textfield',
  );
  $form['return'] = array(
    '#title' => t('Return'),
    '#type' => 'textfield',
  );
  $form['adult'] = array(
    '#title' => t('Adults'),
    '#type' => 'textfield',
    '#size' => 2,
    '#description' => t('(25/59 yrs)'),
    '#default_value' => 1,
  );
  $form['children'] = array(
    '#title' => t('Children'),
    '#type' => 'textfield',
    '#size' => 2,
    '#description' => t('(4/11 yrs)'),
    '#default_value' => 0,
  );

  $form['youths'] = array(
    '#title' => t('Youths'),
    '#type' => 'textfield',
    '#size' => 2,
    '#description' => t('(12/25 yrs)'),
    '#default_value' => 0,
  );

  $form['seniors'] = array(
    '#title' => t('Seniors'),
    '#type' => 'textfield',
    '#size' => 2,
    '#description' => t('(60+ yrs)'),
    '#default_value' => 0,
  );
  $form['kids_tips'] = array(
    '#value' => t('Kids under 4 can travel free'),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Get trains'),
  );

  return $form;
}
/**
 *
 *
 *
 */

function eurostar_train_search_form_validate($form, &$form_state) {
  // validate all BRs here
  
}
/**
 *
 *
 *
 */

function eurostar_train_search_form_submit($form, &$form_state) {
  $form_values = $form_state['values'];
  print_r($form_values);exit;
  unset($form_values['submit']);
  unset($form_values['form_build_id']);
  unset($form_values['form_token']);
  unset($form_values['form_id']);
  unset($form_values['op']);
  
  // Call the search API to get list of train details.
 
}
function eurostar_train_search_autocomplete_from($string = '') {
  $matches = array();

  $matches['key-1'] = 'value-1';
  $matches['key-2'] = 'value-2';
  $matches['key-3'] = 'value-3';
  $matches['key-4'] = 'value-4';

  drupal_json_output($matches);
}
